apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ex-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: python-ex-prod
  template:
    metadata:
      labels:
        app: python-ex-prod
        deploymentconfig: python-ex-prod
    spec:
      containers:
      - image: docker.io/xk96/python-ex-git
        imagePullPolicy: IfNotPresent
        name: python-ex-prod
        ports:
        - containerPort: 8080
          protocol: TCP
