apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ex-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: python-ex-prod
  template:
    metadata:
      labels:
        app: python-ex-prod
        deploymentconfig: python-ex-prod
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ruitest7/python-ex@sha256:a04c59c176f0ec05383e52724f09e844605a4b7780455da5619aff8c51aee49b
        imagePullPolicy: Always
        name: python-ex-prod
        ports:
        - containerPort: 8080
          protocol: TCP
