apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ex
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-ex
        deploymentconfig: python-ex
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ruitest1/python-ex@sha256:3c10eba4267784285340e293c401d3a4f2dde40139441e7700a56a87db5482b7
        imagePullPolicy: Always
        name: python-ex
        ports:
        - containerPort: 8080
          protocol: TCP
